---
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

builds:
  - id: exec
    main: ./cmd/dashboardctl
    binary: dashboardctl
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -extldflags "-static" -X "github.com/cloudpunks/dashboardctl/pkg/version.String={{.Version}}" -X "github.com/cloudpunks/dashboardctl/pkg/version.Revision={{.Commit}}" -X "github.com/cloudpunks/dashboardctl/pkg/version.Date={{.Date}}"
    tags:
      - netgo
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - "386"
      - arm64
      - arm
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: arm

archives:
  - id: exec
    ids:
      - exec
    name_template: "dashboardctl-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}-{{ . }}{{ end }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - CHANGELOG.md
      - src: cmd/dashboardctl/README.md
        dst: README.md

signs:
  - id: archives
    signature: "${artifact}.sig"
    cmd: cosign
    artifacts: all
    certificate: "${artifact}.pem"
    output: true
    args:
      - sign-blob
      - '--oidc-provider=github-actions'
      - '--output-certificate=${certificate}'
      - '--output-signature=${signature}'
      - '${artifact}'
      - --yes

snapshot:
  version_template: testing

changelog:
  disable: true

checksum:
  disable: false
  split: true

...
